### PR TITLE
Add ExpandableList Activity

### PR DESCRIPTION
**Pull request by LeSuisse**
Hi,
On my app I need an expandablelist so basing myself on your ListActivity I have add an ExpandableListActivity.

### CODE REVIEW

**Comment by zetxek** [comment]
Oh! This commit is pretty cool, as I needed this too: I cannot figure out the way to use the ActionBar in my ExpandableListActivity...

**Comment by zetxek** [comment]
Please correct me if I'm wrong, but shouldn't GDExpandableListActivity have a method called "getExpandableListView"?

```
public ExpandableListView getExpandableListView(){
    return mList;
}
```

This way you can access the listView in the GDExpandableListActivity, and make things like the ones I did with the vanilla ExpandableListActivity:

getExpandableListView().setGroupIndicator(getResources().getDrawable(R.drawable.expandable_list_icon));
getExpandableListView().expandGroup(0);

**Comment by cyrilmottier** [comment]
LeSuisse, you are right about adding a `GDExpandableListActivity` to GreenDroid. Personally I hate `ExpandableListView`s but I think this has to be merged to GreenDroid. I'll take a look at your pull request very soon and I'll make sure the APIs are exactly similar to those provided by `ExpandableListActivity`.

**Comment by LeSuisse** [comment]
zetxek, you are right, I forgot `getExpandableListView()` but I fixed this in my last commit.

cyrilmottier I am sorry for commit e397c6e419ac64366df94fd0217e638fe51de128, I did not want it to appear in the pull request. I'm a new user of Git and GitHub.

**Pull request closed without merging**
