### PR TITLE
renamed GDActivity.getActionBar() to GDActivity.getGDActionBar()

### PR DESCRIPTION
**Pull request by khernyo**
It's conflicting with Android 3.0+ Activity.getActionBar()

### CODE REVIEW

**Comment by cyrilmottier** [comment]
Hi szabolcsberecz,

This will be merged very soon. Thank you!

Cyril

**Comment by green-coder** [comment]
+1 for Szaboics on this issue, and I remind Cyril that without this, greendroid doesn't compile on recent APIs. Ca serait bien de faire le merge.

**Comment by radzio** [comment]
So when you will merge this :>?

**Comment by JosephPeng** [comment]
@cyrilmottier I am(we are) looking for your merging~

**Comment by danigonlinea** [comment]
It's easy to implement this. Only you have to do is rename all getActionBar you find as getGDActionBar on Greendroid proyect.

**Comment by dorinionescu** [comment]
4 more errors like
1. GDActivity is not abstract and does not override abstract method getActionBar() in ActionBarActivity
2. getActionBar() in Activity cannot implement getActionBar() in ActionBarActivity
return type android.app.ActionBar is not compatible with greendroid.widget.ActionBar
3. getActionBar() in Activity cannot implement getActionBar() in ActionBarActivity
return type android.app.ActionBar is not compatible with greendroid.widget.ActionBar
4. GDTabActivity is not abstract and does not override abstract method getActionBar() in ActionBarActivity

**Comment by ngohr** [comment]
You shouldt merge it. It is a big barrier for your new users.
I was pleased to test your libary...

**Pull request closed without merging**
