### PR TITLE
Pull request

### PR DESCRIPTION
**Pull request by voidberg**
Hi Cyril,

First of all thanks for GreenDroid, it helped my android development a lot. :)

I made two changes which I think might interest you so I'm sending a pull request. What I did:
- Added a new activity which inherits the MapActivity.
- Added support for configurable number of max action bar items (I needed 5 in my application).

Best,
Alexandru Badiu

### CODE REVIEW

**Comment by cyrilmottier** [comment]
Hi !

Thank you very much for this pull request.
I'm really sorry but I think I won't merge it at least not entirely ...

I have already developed a GDMapActivity internally but as I don't have a lot of time to prepare a new GreenDroid release it still need to be pushed ... I'm sure this will be done really soon ;).

Concerning the maximum amount of items in the ActionBar, I've done this intentionally. Having more than 3 ActionBarItems is something that should be, to my opinion, impossible because it's makes the UI less clear. Google also suggested at the Google I/O 2010, 3 items is a maximum ...

I'm not completely strict about this but I'll try to think about it.

**Comment by cdsap** [comment]
Hi Cyril!!!  I´m very interested in GDMapActivity,  great work...

**Comment by cyrilmottier** [comment]
GDMapActivity is now available in GreenDroid

**Comment by s690716** [comment]
The intentional limit to three items in the action bar is a good solution, but I would also prefer the option to set the limit instead of changing code in the GreenDroid source. A limit of three items is perfect for a portrait orientation on a smartphone. But more contextual items in landscape mode or on a tablet makes an app more user friendly

**Pull request closed without merging**
